export const AUTHORIZE = "AUTHORIZE";
export const AUTHORIZE_SUCCESS = "AUTHORIZE_SUCCESS";
export const AUTHORIZE_FAILURE = "AUTHORIZE_FAILURE";
export const CHECK_AUTHORIZATION = "CHECK_AUTHORIZATION";
export const LOGOUT = "LOGOUT";
export const WRITE_OFF_BET = "WRITE_OFF_BET";
export const CHARGE_WINNINGS = "CHARGE_WINNINGS";
